# Generated by Django 5.2.7 on 2025-11-06 14:03

import albums.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='Allowed formats: mp3 , wav', upload_to=albums.models.song_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(help_text='Allowed formats: png , jpg , jpeg', upload_to=albums.models.song_image_upload_to, validators=[albums.models.validate_image_file_extension]),
        ),
    ]
